name: seqfold2d_gpu
channels:
  - defaults
  - paddle
  - conda-forge
dependencies:
  - python=3.10
  - paddlepaddle-gpu==2.4.2
  - cudatoolkit=11.6
  - matplotlib
  - pandas
  - numpy
  - scikit-learn
  - optuna
  - scipy
  - tqdm
  - colorlog
