name: seqfold2d_cpu
channels:
  - defaults
  - paddle
  - conda-forge
dependencies:
  - python=3.10
  - paddlepaddle==2.4.2
  - numpy
  - scipy
  - tqdm
  - pandas
  - matplotlib
  - colorlog
  - scikit-learn
  - optuna
